In [62]:
import pandas as pd
import requests
import json
from bs4 import BeautifulSoup as bs

In [68]:
key="python"
page=1
l=[]

while page != 0 :

    url="https://internshala.com/internships/keywords-"+key+"/page-"+ str(page)
    r=requests.get(url)
    c=r.content
    soup=bs(c,"html.parser")
    all=soup.find_all("div",{"class":"container-fluid individual_internship"})
    
    #test if isLastPage=1
    test=soup.find("input",{"id":"isLastPage"})
    if test["value"] == "1":
        page=0
    else:
        page+=1

    
    """
    Title, By, Location, Stipend, Duration, Skills, URL
    """
    for item in all:
        d={}
        #Title
        title=item.find("h4")
        try:
            d["Title"]=title["title"]
        except:
            pass
        #By
        by=item.find("a",{"class":"link_display_like_text"})
        try:
            d["By"]=by.text.strip()

        except:
            pass

        #URL
        link=item.find_all("a")
        try:
            d["URL"]="https://www.internshala.com"+[a["href"] for a in link if a["href"].startswith("/internship/detail/")][0]
        except:
            pass

        #Location
        location=item.find("a",{"class":"location_link"})
        try:
            d["Location"]=location.text
        except:
            pass

        #Stipend
        stipend=item.find("i",{"class":"fa fa-inr"})
        try:
            d["Stipend"]="INR " + stipend.next_sibling.strip()
        except:
            pass

        #Duration
        duration=item.find_all("td")
        try:
            d["Duration"]=duration[1].text.strip()
        except:
            pass

        #Skills
        try:
            r1=requests.get(d["URL"])
            c1=r1.content
            soup1=bs(c1,"html.parser")
            skills=soup1.find("span",{"id":"skillNames"})
            d["Skills"]=skills.get_text()
        except:
            pass
        l.append(d)
    print(page)

2
3
0

In [69]:
df=pd.DataFrame(l)
df

,Title,By,URL,Location,Stipend,Duration,Skills
0,Dashboard Development,Blackcoffer,https://www.internshala.com/internship/detail/...,Work From Home,INR 6000-10000 /Month,6 Months,"HTML (Learn HTML), CSS (Learn CSS), JavaScript..."
1,Python Development,FreightBro,https://www.internshala.com/internship/detail/...,Chennai,INR 15000 /Month,3 Months,"MySQL, Python (Learn Python) and Django"
2,Content Writing (Java & Python Programming),Perfectice Eduventure Limited,https://www.internshala.com/internship/detail/...,Work From Home,INR 7000 /Month,2 Months,Java (Learn Java) and Python (Learn Python)
3,Machine Learning (Computer Vision),Modaka Technologies Private Limited,https://www.internshala.com/internship/detail/...,Bangalore,INR 3000-5000 /Month,4 Months,"JavaScript, OpenCV, Python (Learn Python) and ..."
4,Python Development,ZIGRAM,https://www.internshala.com/internship/detail/...,Gurgaon,INR 10000 /Month,6 Months,"Cloud Computing, Python (Learn Python), SQL, D..."
...,...,...,...,...,...,...,...
71,Python/Django Development,Mudraksh And McShaw Advisory,https://www.internshala.com/internship/detail/...,Noida,INR 6000 /Month,3 Months,SQL
72,Web Development,RAPS iTECH,https://www.internshala.com/internship/detail/...,Chandigarh,INR 2500 /Month,6 Months,"HTML (Learn HTML), CSS (Learn CSS) and JavaScript"
73,Python/Django Development,Credicxo Tech Private Limited,https://www.internshala.com/internship/detail/...,Delhi,INR 15000 /Month,3 Months,"Python (Learn Python), SQL, MongoDB, Django, J..."
74,Python Development,Aester India Private Limited,https://www.internshala.com/internship/detail/...,Kochi,INR 2000 /Month,2 Months,"Java (Learn Java), PHP (Learn PHP), Python (Le..."
75,Python Development,Rewoke Technologies,NaN,Bhubaneswar,INR 5000-10000 /Month,2 Months,NaN

In [70]:
df.to_csv('python.csv')